name: 'HCL OneTest Server Action'
description: 'Execute OneTest Server Test from GitHub Action'
inputs:
  serverUrl:
    description: 'OTS URL'
    required: true
  offlineToken:
    description: 'OTS OfflineToken'
    required: true
  teamspace:
    description: 'OTS Teamspace'
    required: true
  project:
    description: 'OTS Project'
    required: true
  branch:
    description: 'OTS branch'
    required: true
  repository:
    description: 'OTS repository'
    required: true
  filepath:
    description: 'OTS FilePath'
    required: true
  variables:
    description: 'OTS variables'
    required: false
  datasets:
    description: 'OTS datasets'
    required: false
  tags:
    description: 'OTS tags'
    required: false
  secretsCollection:
    description: 'OTS Secrets Collection'
    required: false
  startDate:
    description: 'OTS startDate'
    required: false          
runs:
  using: 'node16'
  main: 'index.js'